/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ParticipantIndexRouteImport } from './routes/participant/index'
import { Route as CoachIndexRouteImport } from './routes/coach/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ParticipantSettingsRouteImport } from './routes/participant/settings'
import { Route as ParticipantScheduleRouteImport } from './routes/participant/schedule'
import { Route as ParticipantNotificationsRouteImport } from './routes/participant/notifications'
import { Route as ParticipantFilesRouteImport } from './routes/participant/files'
import { Route as ParticipantDocumentsRouteImport } from './routes/participant/documents'
import { Route as ParticipantAbsenceRouteImport } from './routes/participant/absence'
import { Route as CoachSettingsRouteImport } from './routes/coach/settings'
import { Route as CoachScheduleRouteImport } from './routes/coach/schedule'
import { Route as CoachNotificationsRouteImport } from './routes/coach/notifications'
import { Route as CoachMonitoringRouteImport } from './routes/coach/monitoring'
import { Route as CoachFilesRouteImport } from './routes/coach/files'
import { Route as CoachDocumentsRouteImport } from './routes/coach/documents'
import { Route as CoachAbsencesRouteImport } from './routes/coach/absences'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminParticipantsRouteImport } from './routes/admin/participants'
import { Route as AdminNotificationsRouteImport } from './routes/admin/notifications'
import { Route as AdminMonitoringRouteImport } from './routes/admin/monitoring'
import { Route as AdminFilesRouteImport } from './routes/admin/files'
import { Route as AdminDocumentsRouteImport } from './routes/admin/documents'
import { Route as AdminDepartmentsRouteImport } from './routes/admin/departments'
import { Route as AdminCoachesRouteImport } from './routes/admin/coaches'
import { Route as AdminAbsencesRouteImport } from './routes/admin/absences'
import { Route as CoachParticipantsIndexRouteImport } from './routes/coach/participants/index'
import { Route as CoachParticipantsIdRouteImport } from './routes/coach/participants/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipantIndexRoute = ParticipantIndexRouteImport.update({
  id: '/participant/',
  path: '/participant/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachIndexRoute = CoachIndexRouteImport.update({
  id: '/coach/',
  path: '/coach/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipantSettingsRoute = ParticipantSettingsRouteImport.update({
  id: '/participant/settings',
  path: '/participant/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipantScheduleRoute = ParticipantScheduleRouteImport.update({
  id: '/participant/schedule',
  path: '/participant/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipantNotificationsRoute =
  ParticipantNotificationsRouteImport.update({
    id: '/participant/notifications',
    path: '/participant/notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const ParticipantFilesRoute = ParticipantFilesRouteImport.update({
  id: '/participant/files',
  path: '/participant/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipantDocumentsRoute = ParticipantDocumentsRouteImport.update({
  id: '/participant/documents',
  path: '/participant/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipantAbsenceRoute = ParticipantAbsenceRouteImport.update({
  id: '/participant/absence',
  path: '/participant/absence',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachSettingsRoute = CoachSettingsRouteImport.update({
  id: '/coach/settings',
  path: '/coach/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachScheduleRoute = CoachScheduleRouteImport.update({
  id: '/coach/schedule',
  path: '/coach/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachNotificationsRoute = CoachNotificationsRouteImport.update({
  id: '/coach/notifications',
  path: '/coach/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachMonitoringRoute = CoachMonitoringRouteImport.update({
  id: '/coach/monitoring',
  path: '/coach/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachFilesRoute = CoachFilesRouteImport.update({
  id: '/coach/files',
  path: '/coach/files',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachDocumentsRoute = CoachDocumentsRouteImport.update({
  id: '/coach/documents',
  path: '/coach/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachAbsencesRoute = CoachAbsencesRouteImport.update({
  id: '/coach/absences',
  path: '/coach/absences',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminParticipantsRoute = AdminParticipantsRouteImport.update({
  id: '/admin/participants',
  path: '/admin/participants',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMonitoringRoute = AdminMonitoringRouteImport.update({
  id: '/admin/monitoring',
  path: '/admin/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFilesRoute = AdminFilesRouteImport.update({
  id: '/admin/files',
  path: '/admin/files',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/admin/documents',
  path: '/admin/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDepartmentsRoute = AdminDepartmentsRouteImport.update({
  id: '/admin/departments',
  path: '/admin/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoachesRoute = AdminCoachesRouteImport.update({
  id: '/admin/coaches',
  path: '/admin/coaches',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAbsencesRoute = AdminAbsencesRouteImport.update({
  id: '/admin/absences',
  path: '/admin/absences',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachParticipantsIndexRoute = CoachParticipantsIndexRouteImport.update({
  id: '/coach/participants/',
  path: '/coach/participants/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachParticipantsIdRoute = CoachParticipantsIdRouteImport.update({
  id: '/coach/participants/$id',
  path: '/coach/participants/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/absences': typeof AdminAbsencesRoute
  '/admin/coaches': typeof AdminCoachesRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/files': typeof AdminFilesRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/coach/absences': typeof CoachAbsencesRoute
  '/coach/documents': typeof CoachDocumentsRoute
  '/coach/files': typeof CoachFilesRoute
  '/coach/monitoring': typeof CoachMonitoringRoute
  '/coach/notifications': typeof CoachNotificationsRoute
  '/coach/schedule': typeof CoachScheduleRoute
  '/coach/settings': typeof CoachSettingsRoute
  '/participant/absence': typeof ParticipantAbsenceRoute
  '/participant/documents': typeof ParticipantDocumentsRoute
  '/participant/files': typeof ParticipantFilesRoute
  '/participant/notifications': typeof ParticipantNotificationsRoute
  '/participant/schedule': typeof ParticipantScheduleRoute
  '/participant/settings': typeof ParticipantSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/coach/': typeof CoachIndexRoute
  '/participant/': typeof ParticipantIndexRoute
  '/coach/participants/$id': typeof CoachParticipantsIdRoute
  '/coach/participants/': typeof CoachParticipantsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/absences': typeof AdminAbsencesRoute
  '/admin/coaches': typeof AdminCoachesRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/files': typeof AdminFilesRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/coach/absences': typeof CoachAbsencesRoute
  '/coach/documents': typeof CoachDocumentsRoute
  '/coach/files': typeof CoachFilesRoute
  '/coach/monitoring': typeof CoachMonitoringRoute
  '/coach/notifications': typeof CoachNotificationsRoute
  '/coach/schedule': typeof CoachScheduleRoute
  '/coach/settings': typeof CoachSettingsRoute
  '/participant/absence': typeof ParticipantAbsenceRoute
  '/participant/documents': typeof ParticipantDocumentsRoute
  '/participant/files': typeof ParticipantFilesRoute
  '/participant/notifications': typeof ParticipantNotificationsRoute
  '/participant/schedule': typeof ParticipantScheduleRoute
  '/participant/settings': typeof ParticipantSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/coach': typeof CoachIndexRoute
  '/participant': typeof ParticipantIndexRoute
  '/coach/participants/$id': typeof CoachParticipantsIdRoute
  '/coach/participants': typeof CoachParticipantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/absences': typeof AdminAbsencesRoute
  '/admin/coaches': typeof AdminCoachesRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/files': typeof AdminFilesRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/coach/absences': typeof CoachAbsencesRoute
  '/coach/documents': typeof CoachDocumentsRoute
  '/coach/files': typeof CoachFilesRoute
  '/coach/monitoring': typeof CoachMonitoringRoute
  '/coach/notifications': typeof CoachNotificationsRoute
  '/coach/schedule': typeof CoachScheduleRoute
  '/coach/settings': typeof CoachSettingsRoute
  '/participant/absence': typeof ParticipantAbsenceRoute
  '/participant/documents': typeof ParticipantDocumentsRoute
  '/participant/files': typeof ParticipantFilesRoute
  '/participant/notifications': typeof ParticipantNotificationsRoute
  '/participant/schedule': typeof ParticipantScheduleRoute
  '/participant/settings': typeof ParticipantSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/coach/': typeof CoachIndexRoute
  '/participant/': typeof ParticipantIndexRoute
  '/coach/participants/$id': typeof CoachParticipantsIdRoute
  '/coach/participants/': typeof CoachParticipantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin/absences'
    | '/admin/coaches'
    | '/admin/departments'
    | '/admin/documents'
    | '/admin/files'
    | '/admin/monitoring'
    | '/admin/notifications'
    | '/admin/participants'
    | '/admin/reports'
    | '/admin/settings'
    | '/coach/absences'
    | '/coach/documents'
    | '/coach/files'
    | '/coach/monitoring'
    | '/coach/notifications'
    | '/coach/schedule'
    | '/coach/settings'
    | '/participant/absence'
    | '/participant/documents'
    | '/participant/files'
    | '/participant/notifications'
    | '/participant/schedule'
    | '/participant/settings'
    | '/admin/'
    | '/coach/'
    | '/participant/'
    | '/coach/participants/$id'
    | '/coach/participants/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/absences'
    | '/admin/coaches'
    | '/admin/departments'
    | '/admin/documents'
    | '/admin/files'
    | '/admin/monitoring'
    | '/admin/notifications'
    | '/admin/participants'
    | '/admin/reports'
    | '/admin/settings'
    | '/coach/absences'
    | '/coach/documents'
    | '/coach/files'
    | '/coach/monitoring'
    | '/coach/notifications'
    | '/coach/schedule'
    | '/coach/settings'
    | '/participant/absence'
    | '/participant/documents'
    | '/participant/files'
    | '/participant/notifications'
    | '/participant/schedule'
    | '/participant/settings'
    | '/admin'
    | '/coach'
    | '/participant'
    | '/coach/participants/$id'
    | '/coach/participants'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/admin/absences'
    | '/admin/coaches'
    | '/admin/departments'
    | '/admin/documents'
    | '/admin/files'
    | '/admin/monitoring'
    | '/admin/notifications'
    | '/admin/participants'
    | '/admin/reports'
    | '/admin/settings'
    | '/coach/absences'
    | '/coach/documents'
    | '/coach/files'
    | '/coach/monitoring'
    | '/coach/notifications'
    | '/coach/schedule'
    | '/coach/settings'
    | '/participant/absence'
    | '/participant/documents'
    | '/participant/files'
    | '/participant/notifications'
    | '/participant/schedule'
    | '/participant/settings'
    | '/admin/'
    | '/coach/'
    | '/participant/'
    | '/coach/participants/$id'
    | '/coach/participants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AdminAbsencesRoute: typeof AdminAbsencesRoute
  AdminCoachesRoute: typeof AdminCoachesRoute
  AdminDepartmentsRoute: typeof AdminDepartmentsRoute
  AdminDocumentsRoute: typeof AdminDocumentsRoute
  AdminFilesRoute: typeof AdminFilesRoute
  AdminMonitoringRoute: typeof AdminMonitoringRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminParticipantsRoute: typeof AdminParticipantsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  CoachAbsencesRoute: typeof CoachAbsencesRoute
  CoachDocumentsRoute: typeof CoachDocumentsRoute
  CoachFilesRoute: typeof CoachFilesRoute
  CoachMonitoringRoute: typeof CoachMonitoringRoute
  CoachNotificationsRoute: typeof CoachNotificationsRoute
  CoachScheduleRoute: typeof CoachScheduleRoute
  CoachSettingsRoute: typeof CoachSettingsRoute
  ParticipantAbsenceRoute: typeof ParticipantAbsenceRoute
  ParticipantDocumentsRoute: typeof ParticipantDocumentsRoute
  ParticipantFilesRoute: typeof ParticipantFilesRoute
  ParticipantNotificationsRoute: typeof ParticipantNotificationsRoute
  ParticipantScheduleRoute: typeof ParticipantScheduleRoute
  ParticipantSettingsRoute: typeof ParticipantSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CoachIndexRoute: typeof CoachIndexRoute
  ParticipantIndexRoute: typeof ParticipantIndexRoute
  CoachParticipantsIdRoute: typeof CoachParticipantsIdRoute
  CoachParticipantsIndexRoute: typeof CoachParticipantsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participant/': {
      id: '/participant/'
      path: '/participant'
      fullPath: '/participant/'
      preLoaderRoute: typeof ParticipantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/': {
      id: '/coach/'
      path: '/coach'
      fullPath: '/coach/'
      preLoaderRoute: typeof CoachIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participant/settings': {
      id: '/participant/settings'
      path: '/participant/settings'
      fullPath: '/participant/settings'
      preLoaderRoute: typeof ParticipantSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participant/schedule': {
      id: '/participant/schedule'
      path: '/participant/schedule'
      fullPath: '/participant/schedule'
      preLoaderRoute: typeof ParticipantScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participant/notifications': {
      id: '/participant/notifications'
      path: '/participant/notifications'
      fullPath: '/participant/notifications'
      preLoaderRoute: typeof ParticipantNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participant/files': {
      id: '/participant/files'
      path: '/participant/files'
      fullPath: '/participant/files'
      preLoaderRoute: typeof ParticipantFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participant/documents': {
      id: '/participant/documents'
      path: '/participant/documents'
      fullPath: '/participant/documents'
      preLoaderRoute: typeof ParticipantDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participant/absence': {
      id: '/participant/absence'
      path: '/participant/absence'
      fullPath: '/participant/absence'
      preLoaderRoute: typeof ParticipantAbsenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/settings': {
      id: '/coach/settings'
      path: '/coach/settings'
      fullPath: '/coach/settings'
      preLoaderRoute: typeof CoachSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/schedule': {
      id: '/coach/schedule'
      path: '/coach/schedule'
      fullPath: '/coach/schedule'
      preLoaderRoute: typeof CoachScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/notifications': {
      id: '/coach/notifications'
      path: '/coach/notifications'
      fullPath: '/coach/notifications'
      preLoaderRoute: typeof CoachNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/monitoring': {
      id: '/coach/monitoring'
      path: '/coach/monitoring'
      fullPath: '/coach/monitoring'
      preLoaderRoute: typeof CoachMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/files': {
      id: '/coach/files'
      path: '/coach/files'
      fullPath: '/coach/files'
      preLoaderRoute: typeof CoachFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/documents': {
      id: '/coach/documents'
      path: '/coach/documents'
      fullPath: '/coach/documents'
      preLoaderRoute: typeof CoachDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/absences': {
      id: '/coach/absences'
      path: '/coach/absences'
      fullPath: '/coach/absences'
      preLoaderRoute: typeof CoachAbsencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/participants': {
      id: '/admin/participants'
      path: '/admin/participants'
      fullPath: '/admin/participants'
      preLoaderRoute: typeof AdminParticipantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/monitoring': {
      id: '/admin/monitoring'
      path: '/admin/monitoring'
      fullPath: '/admin/monitoring'
      preLoaderRoute: typeof AdminMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/files': {
      id: '/admin/files'
      path: '/admin/files'
      fullPath: '/admin/files'
      preLoaderRoute: typeof AdminFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/admin/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/departments': {
      id: '/admin/departments'
      path: '/admin/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AdminDepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/coaches': {
      id: '/admin/coaches'
      path: '/admin/coaches'
      fullPath: '/admin/coaches'
      preLoaderRoute: typeof AdminCoachesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/absences': {
      id: '/admin/absences'
      path: '/admin/absences'
      fullPath: '/admin/absences'
      preLoaderRoute: typeof AdminAbsencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/participants/': {
      id: '/coach/participants/'
      path: '/coach/participants'
      fullPath: '/coach/participants/'
      preLoaderRoute: typeof CoachParticipantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/participants/$id': {
      id: '/coach/participants/$id'
      path: '/coach/participants/$id'
      fullPath: '/coach/participants/$id'
      preLoaderRoute: typeof CoachParticipantsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AdminAbsencesRoute: AdminAbsencesRoute,
  AdminCoachesRoute: AdminCoachesRoute,
  AdminDepartmentsRoute: AdminDepartmentsRoute,
  AdminDocumentsRoute: AdminDocumentsRoute,
  AdminFilesRoute: AdminFilesRoute,
  AdminMonitoringRoute: AdminMonitoringRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminParticipantsRoute: AdminParticipantsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  CoachAbsencesRoute: CoachAbsencesRoute,
  CoachDocumentsRoute: CoachDocumentsRoute,
  CoachFilesRoute: CoachFilesRoute,
  CoachMonitoringRoute: CoachMonitoringRoute,
  CoachNotificationsRoute: CoachNotificationsRoute,
  CoachScheduleRoute: CoachScheduleRoute,
  CoachSettingsRoute: CoachSettingsRoute,
  ParticipantAbsenceRoute: ParticipantAbsenceRoute,
  ParticipantDocumentsRoute: ParticipantDocumentsRoute,
  ParticipantFilesRoute: ParticipantFilesRoute,
  ParticipantNotificationsRoute: ParticipantNotificationsRoute,
  ParticipantScheduleRoute: ParticipantScheduleRoute,
  ParticipantSettingsRoute: ParticipantSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  CoachIndexRoute: CoachIndexRoute,
  ParticipantIndexRoute: ParticipantIndexRoute,
  CoachParticipantsIdRoute: CoachParticipantsIdRoute,
  CoachParticipantsIndexRoute: CoachParticipantsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
